install:
  - npm install
language: node_js
node_js:
  - "6"
script: 
  - "npm test"
sudo: true
deploy:
  edge: true
  provider: cloudfoundry
  username: 05cea16f-606b-457f-9f79-255dd85312da
  password:
    secure: "KVeJotHCfo3wLYOdHhpFcgX717nEsdWCCH7RPMxFSTrjhTh3cPidTYpcS7EJ5rsSZuDl7+W/4z/ZZTkDkNVPaECPxT/j/oJ1DbDbIyqS1+9IgHK/1xsK/OL9k6MCqighrFxBlLviYGpwjUOOXHpQS63yj365QeYlMpTLV+k0hjo="
  api: https://api.fr.cloud.gov
  organization: "gsa-18f-hubot"
  space: "prod"
