version: "3.2"
services:
  database:
    image: postgres:13
    networks:
      - charlie-bot
    environment:
      - POSTGRES_DB=charlie
      - POSTGRES_PASSWORD=charlie-bot
      - POSTGRES_USER=charlie-bot
    ports:
    - 54329:5432

  charlie:
    build: .
    image: 18f/charlie
    networks:
      - charlie-bot
    environment:
      - HOLIDAY_REMINDER_CHANNEL=${HOLIDAY_REMINDER_CHANNEL}
      - HOLIDAY_REMINDER_TIME=${HOLIDAY_REMINDER_TIME}
      - HOLIDAY_REMINDER_TIMEZONE=${HOLIDAY_REMINDER_TIMEZONE}
      - ANGRY_TOCK_FIRST_TIME=${ANGRY_TOCK_FIRST_TIME}
      - ANGRY_TOCK_SECOND_TIME=${ANGRY_TOCK_SECOND_TIME}
      - ANGRY_TOCK_TIMEZONE=${ANGRY_TOCK_TIMEZONE}
      - DATABASE_URL=postgres://charlie-bot:charlie-bot@database/charlie
      - LOG_LEVEL=debug
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - TOCK_API=${TOCK_API}
      - TOCK_TOKEN=${TOCK_TOKEN}
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    links:
      - database:database

networks:
  charlie-bot:
