name: pull requests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        id: depcache
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: install dependencies
        if: steps.depcache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: [build]
    name: lint
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: lint
        run: npm run lint

  test:
    needs: [build]
    name: unit tests
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: run tests
        run: npm test
  
  deploy:
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    name: deploy to cloud.gov
    runs-on: ubuntu-latest
    container: governmentpaas/cf-cli
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: push to cloud.gov
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
        run: |
          cf login -a $CF_API -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
          cf push -f manifest.yml
