name: pull requests

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        id: depcache
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: install dependencies
        if: steps.depcache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: [build]
    name: lint
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: lint
        run: npm run lint

  test:
    needs: [build]
    name: unit tests
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: run tests
        run: npm test
