name: pull requests

on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        id: depcache
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: install dependencies
        if: steps.depcache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: [build]
    name: lint
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: lint
        run: npm run lint

  test:
    needs: [build]
    name: unit tests
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@d1255ad
        with:
          path: ./node_modules
          key: 18f-bot-${{ runner.os }}-${{ hashFiles('package.json') }}-v1
      - name: run tests
        run: npm test
