name: pull requests

on: [pull_request]

jobs:
  lint:
    name: 18F ESLint
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: 18f/18f-eslint-action@v1.1.0
        with:
          lint-glob: "*.js scripts/*.js test/**/*.js"
  test:
    name: unit tests
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - uses: actions/checkout@af513c7a
      - uses: actions/cache@v2
        id: dep-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}-v2
      - name: install dependencies
        if: steps.dep-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: run tests
        run: npm test
